### ISSUE TITLE
dump1090-draw_heatmap.sh problem 

### ISSUE THREAD

**Issue by SA7BNT** [filipsPL/autowx2#47]
Hallo @all 
having this issue. Someone getting the same or is it my system??

`sa7bnt@owncloud:~/autowx2/bin$./dump1090-draw_heatmap.sh` 
/home/sa7bnt/autowx2/
Bruzaholm
Traceback (most recent call last):
  File "/home/sa7bnt/autowx2//bin/heatmap.py", line 1299, in <module>
    main()
  File "/home/sa7bnt/autowx2//bin/heatmap.py", line 1277, in main
    config.fill_missing()
  File "/home/sa7bnt/autowx2//bin/heatmap.py", line 1226, in fill_missing
    self.extent_in = Extent(shapes=self.shapes)
  File "/home/sa7bnt/autowx2//bin/heatmap.py", line 247, in __init__
    raise ValueError('Extent must be initialized')
ValueError: Extent must be initialized
Traceback (most recent call last):
  File "/home/sa7bnt/autowx2//bin/heatmap.py", line 1299, in <module>
    main()
  File "/home/sa7bnt/autowx2//bin/heatmap.py", line 1277, in main
    config.fill_missing()
  File "/home/sa7bnt/autowx2//bin/heatmap.py", line 1226, in fill_missing
    self.extent_in = Extent(shapes=self.shapes)
  File "/home/sa7bnt/autowx2//bin/heatmap.py", line 247, in __init__
    raise ValueError('Extent must be initialized')
ValueError: Extent must be initialized
Traceback (most recent call last):
  File "/home/sa7bnt/autowx2//bin/heatmap.py", line 1299, in <module>
    main()
  File "/home/sa7bnt/autowx2//bin/heatmap.py", line 1277, in main
    config.fill_missing()
  File "/home/sa7bnt/autowx2//bin/heatmap.py", line 1226, in fill_missing
    self.extent_in = Extent(shapes=self.shapes)
  File "/home/sa7bnt/autowx2//bin/heatmap.py", line 247, in __init__
    raise ValueError('Extent must be initialized')
ValueError: Extent must be initialized
Traceback (most recent call last):
  File "/home/sa7bnt/autowx2//bin/heatmap.py", line 1299, in <module>
    main()
  File "/home/sa7bnt/autowx2//bin/heatmap.py", line 1277, in main
    config.fill_missing()
  File "/home/sa7bnt/autowx2//bin/heatmap.py", line 1226, in fill_missing
    self.extent_in = Extent(shapes=self.shapes)
  File "/home/sa7bnt/autowx2//bin/heatmap.py", line 247, in __init__
    raise ValueError('Extent must be initialized')
ValueError: Extent must be initialized
convert-im6.q16: unable to open image `/home/sa7bnt/autowx2//var/www/recordings//dump1090//heatmap-osm.png': No such file or directory @ error/blob.c/OpenBlob/2701.
convert-im6.q16: no images defined `/home/sa7bnt/autowx2//var/www/recordings//dump1090//heatmap-osm.jpg' @ error/convert.c/ConvertImageCommand/3258.
convert-im6.q16: unable to open image `/home/sa7bnt/autowx2//var/www/recordings//dump1090//heatmap-osm2.png': No such file or directory @ error/blob.c/OpenBlob/2701.
convert-im6.q16: no images defined `/home/sa7bnt/autowx2//var/www/recordings//dump1090//heatmap-osm2.jpg' @ error/convert.c/ConvertImageCommand/3258.
rm: cannot remove '/tmp/h1.png': No such file or directory
rm: cannot remove '/tmp/h2.png': No such file or directory
rm: cannot remove '/home/sa7bnt/autowx2//var/www/recordings//dump1090//heatmap-osm.png': No such file or directory
rm: cannot remove '/home/sa7bnt/autowx2//var/www/recordings//dump1090//heatmap-osm2.png': No such file or directory
sa7bnt@owncloud:~/autowx2/bin$

**Comment by filipsPL** [comment]
I think this script is not useful. I'm considering removing it... Maybe something better would be more applicable for visualization of the airplane positions...
